
options(repos = c(CRAN = "https://cloud.r-project.org"))

install.packages("devtools")
install.packages("remotes")

remotes::install_version("shiny", version = "1.10.0", force = T)
remotes::install_version("shinythemes", version = "1.2.0", force = T)
remotes::install_version("shinyjqui", version = "0.4.1", force = T)
remotes::install_version("shinycssloaders", version = "1.1.0", force = T)
remotes::install_version("shinyWidgets", version = "0.9.0", force = T)
remotes::install_version("dplyr", version = "1.1.4", force = T)
remotes::install_version("tidyr", version = "1.3.1", force = T)
remotes::install_version("readr", version = "2.1.5", force = T)
remotes::install_version("ggplot2", version = "3.5.2", force = T)
remotes::install_version("DT", version = "0.33", force = T)
remotes::install_version("data.table", version = "1.17.6", force = T)
remotes::install_version("plotly", version = "4.11.0", force = T)
remotes::install_version("stringr", version = "1.5.1", force = T)
remotes::install_version("ggpubr", version = "0.6.1", force = T)
remotes::install_version("ggrepel", version = "0.9.6", force = T)
remotes::install_version("RColorBrewer", version = "1.1-3", force = T)
remotes::install_version("reshape2", version = "1.4.4", force = T)
remotes::install_version("rstatix", version = "0.7.2", force = T)
remotes::install_version("survival", version = "3.8-3", force = T)
remotes::install_version("survminer", version = "0.5.0", force = T)
remotes::install_version("gtsummary", version = "2.2.0", force = T)
remotes::install_version("powerSurvEpi", version = "0.1.5", force = T)
remotes::install_version("readxl", version = "1.4.5", force = T)
remotes::install_version("circlize", version = "0.4.16", force = T)
remotes::install_version("bslib", version = "0.9.0", force = T)
remotes::install_version("shinyjs", version = "2.1.0", force = T)
remotes::install_version("listviewer", version = "4.0.0", force = T)
remotes::install_version("bsicons", version = "0.1.2", force = T)
remotes::install_version("readtext", version = "0.91", force = T)
remotes::install_version("svglite", version = "2.2.1", force = T)

devtools::install_github("davidsjoberg/ggsankey", force = TRUE)
# BiocManager, BiocVersion, S4Vectors, and IRanges are required for ComplexHeatmap
devtools::install_github("Bioconductor/BiocManager", force = TRUE)
# Installed BiocVersion with tar.gz file from this link: https://bioconductor.org/packages/3.19/bioc/src/contrib/BiocVersion_3.19.1.tar.gz
#install.packages("Getting_Started/BiocVersion_3.19.1.tar.gz", repos = NULL, type = "source")
devtools::install_github("Bioconductor/BiocGenerics", force = TRUE)
devtools::install_github("Bioconductor/S4Vectors", force = TRUE)
devtools::install_github("Bioconductor/IRanges", force = TRUE)
devtools::install_github("jokergoo/ComplexHeatmap", force = TRUE)
devtools::install_github("jokergoo/InteractiveComplexHeatmap", force = TRUE)

