
options(warn = -1)
suppressPackageStartupMessages(library(shiny))
suppressPackageStartupMessages(library(shinyjqui))
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(colourpicker))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(library(rstatix))
suppressPackageStartupMessages(library(survival))
suppressPackageStartupMessages(library(survminer))
suppressPackageStartupMessages(library(gtsummary))
suppressPackageStartupMessages(library(powerSurvEpi))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(shinyWidgets))
suppressPackageStartupMessages(library(circlize))
suppressPackageStartupMessages(library(bslib))
suppressPackageStartupMessages(library(shinythemes))
suppressPackageStartupMessages(library(shinycssloaders))
suppressPackageStartupMessages(library(listviewer))
suppressPackageStartupMessages(library(bsicons))
suppressPackageStartupMessages(library(readtext))
suppressPackageStartupMessages(library(svglite))
suppressPackageStartupMessages(library(shinyalert))
suppressPackageStartupMessages(library(ggsankey))
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(InteractiveComplexHeatmap))


